[pytest]
testpaths = tests

filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::UserWarning:pydantic
    ignore::UserWarning:mlflow
    ignore::UserWarning:databricks
