import { useState, useRef, useEffect } from "react";
import { useRegion } from "../context/RegionContext";
import MarkdownRenderer from "./MarkdownRenderer";

interface Props {
  visible: boolean;
  onClose: () => void;
}

export default function RiskBrief({ visible, onClose }: Props) {
  const { market, activeMarket } = useRegion();
  const [content, setContent] = useState("");
  const [loading, setLoading] = useState(false);
  const [generated, setGenerated] = useState(false);
  const esRef = useRef<EventSource | null>(null);

  useEffect(() => {
    if (visible && !generated) generateBrief();
  }, [visible]);

  useEffect(() => {
    if (!visible) {
      esRef.current?.close();
      setContent("");
      setGenerated(false);
      setLoading(false);
    }
  }, [visible]);

  function generateBrief() {
    esRef.current?.close();
    setContent("");
    setLoading(true);
    setGenerated(false);

    const es = new EventSource(`/api/risk-brief?market=${market}`);
    esRef.current = es;

    es.onmessage = (e) => {
      try { setContent((prev) => prev + JSON.parse(e.data)); } catch { /* skip */ }
    };
    es.addEventListener("done", () => {
      es.close();
      setLoading(false);
      setGenerated(true);
    });
    es.onerror = () => {
      es.close();
      setLoading(false);
      setGenerated(true);
      setContent((c) => c || "Failed to generate risk brief. Please try again.");
    };
  }

  if (!visible) return null;

  const marketLabel = activeMarket ? `${activeMarket.flag} ${activeMarket.name}` : market;

  return (
    <div className="briefing-overlay" onClick={onClose}>
      <div className="briefing-modal" style={{ maxWidth: 700 }} onClick={(e) => e.stopPropagation()}>

        <div className="briefing-toolbar">
          <div className="briefing-toolbar-left">
            <span className="briefing-doc-icon" style={{ background: "linear-gradient(135deg,#7C3AED,#5B21B6)" }}>AI</span>
            <span className="briefing-toolbar-title">AI Risk Brief — {marketLabel}</span>
          </div>
          <div className="briefing-toolbar-right">
            {generated && !loading && (
              <button className="briefing-btn" onClick={generateBrief}>Regenerate</button>
            )}
            <button className="briefing-btn briefing-btn-close" onClick={onClose}>✕</button>
          </div>
        </div>

        <div className="briefing-body" style={{ padding: "24px 28px" }}>
          {loading && !content && (
            <div style={{ display: "flex", alignItems: "center", gap: 12, color: "var(--text-muted)", padding: "32px 0" }}>
              <div className="loading-spinner" />
              <span style={{ fontSize: 14 }}>Analysing regulatory posture for {marketLabel}…</span>
            </div>
          )}
          {content && (
            <div style={{ fontSize: 14, lineHeight: 1.75 }}>
              <MarkdownRenderer content={content} />
              {loading && <span className="typing-cursor">▌</span>}
            </div>
          )}
        </div>

        <div style={{ padding: "10px 24px", borderTop: "1px solid var(--border)", fontSize: 11, color: "var(--text-muted)", textAlign: "right" }}>
          Generated by Databricks Foundation Model API · {new Date().toLocaleDateString("en-AU", { day: "numeric", month: "long", year: "numeric" })}
        </div>
      </div>
    </div>
  );
}
